#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cliff
Version  : 2.13.0
Release  : 43
URL      : https://pypi.debian.net/cliff/cliff-2.13.0.tar.gz
Source0  : https://pypi.debian.net/cliff/cliff-2.13.0.tar.gz
Summary  : Command Line Interface Formulation Framework
Group    : Development/Tools
License  : Apache-2.0
Requires: cliff-python3
Requires: cliff-license
Requires: cliff-python
Requires: PyYAML
Requires: Sphinx
Requires: cliff
Requires: cmd2
Requires: pbr
Requires: pyparsing
Requires: six
Requires: stevedore
Requires: unicodecsv
BuildRequires : buildreq-distutils3
BuildRequires : cliff
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Team and repository tags
        ========================

%package license
Summary: license components for the cliff package.
Group: Default

%description license
license components for the cliff package.


%package python
Summary: python components for the cliff package.
Group: Default
Requires: cliff-python3

%description python
python components for the cliff package.


%package python3
Summary: python3 components for the cliff package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cliff package.


%prep
%setup -q -n cliff-2.13.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532211274
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/cliff
cp LICENSE %{buildroot}/usr/share/doc/cliff/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/cliff/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
